---
FilterPropertyType: "Land"
FilterState: "MD"
LoopNet:
  criteria:
    LNPropertyTypes: 512
    LNIndustrialSubtypes: 0
    LNRetailSubtypes: 0
    LNShoppingCenterSubtypes: 0
    LNMultiFamilySubtypes: 0
    LNSpecialtySubtypes: 0
    LNOfficeSubtypes: 0
    LNHealthCareSubtypes: 0
    LNHospitalitySubtypes: 0
    LNSportsAndEntertainmentSubtypes: 0
    LNLandSubtypes: 0
    PropertyTypes: 4
    HospitalitySubtypes: 0
    IndustrialSubtypes: 0
    LandTypes: 0
    OfficeSubtypes: 0
    GeneralRetailSubtypes: 0
    FlexSubtypes: 0
    SportsAndEntertainmentSubtypes: 0
    SpecialtySubtypes: 0
    MultifamilySubtypes: 0
    HealthcareSubtypes: 0
    ShoppingCenterTypes: 0
    ApartmentStyleTypes: 0
    Country: US
    Region: ''
    State: MD
    Market:
    MSA:
    County:
    City: ''
    PostalCode:
    GeographyFilters:
    - ID:
      BoundingBox:
      - -79.4871439
      - 37.91205
      - -75.0458981
      - 39.723143
      Centroid:
      - -77.266521
      - 38.8175965
      Display: Maryland
      TypeaheadDisplay: Maryland - USA
      GeographyId: 21
      Code: MD
      GeographyType: 1
      Radius: 0
      RadiusLengthMeasure: 0
      SubmarketPropertyType: 0
      Address:
      MatchType: 11
    PageLocationLabel: MD
    TypeaheadLocationLabel: Maryland - USA
    IncludeProximityCities: false
    AddressLine:
    Distance: 0
    Radius:
    CoordinateBounds:
    Polygon:
    HasValidCoordinates:
    BuildingClass: 0
    BuildingSizeUom: SquareFeet
    LotSizeUom: Acres
    SubCategoryList:
    - 101
    - 102
    - 105
    - 501
    - 917
    - 503
    - 504
    - 505
    - 507
    - 508
    - 509
    - 512
    - 513
    Editor: Universal
    PreserveAddressForRadiusSavedSearch: false
    ListingSearchType: 1
    OnMarketDateRange:
    Keywords:
    Sorting: []
    LoopLinkForLeaseDefaultSorting: []
    LoopLinkForSaleDefaultSorting: []
    LoopLinkForSaleAndLeaseDefaultSorting: []
    PropertyGroupId:
    HasMultipleLocations: false
    IsForSale: true
    PriceRangeMin:
    PriceRangeMax:
    BuildingSizeRangeMin:
    BuildingSizeRangeMax:
    PriceRangeCurrency: USD
    PriceRangeRateType: Total
    LotSizeRangeMin:
    LotSizeRangeMax:
    UnitCountRangeMin:
    UnitCountRangeMax:
    CapRateRangeMin:
    CapRateRangeMax:
    YearBuiltRangeMin:
    YearBuiltRangeMax:
    TermLengthRangeMin:
    TermLengthRangeMax:
    NetLeased: false
    InContract: true
    Distressed: false
    Auction: true
    IsTenXAuctions: false
    AuctionIds:
    Single: false
    Multiple: false
    InvestmentTypeCore: false
    InvestmentTypeValueAdd: false
    InvestmentTypeOpportunistic: false
    InvestmentTypeTripleNet: false
    InvestmentTypeOpportunityZone: false
    AuctionAssetTypeProperties: false
    AuctionAssetTypeNotes: false
    AuctionFinanceTypeFinancing:
    AuctionFinanceTypeBrokerCoOp:
    BusinessForSale: true
    VacantOwner: true
    Investment: true
    InOpportunityZone:
    CondosFilter: 0
    PortfoliosFilter: 0
    ShoppingCenterFilter: 0
    BuildingParkFilter: 0
    IsForLease: false
    LeaseRateRangeMin:
    LeaseRateRangeMax:
    SpaceAvailableRangeMin:
    SpaceAvailableRangeMax:
    LeaseRateTerm:
    SpaceAvailableUom:
    LeaseRateCurrency:
    LeaseRatePerSizeUom:
    SubLease: false
    RegionalMarket:
    SubMarket:
    MoveInDateIndicator: 0
    MoveInDateEnteredType:
    MoveInDateEnteredRangeMin:
    MoveInDateEnteredRangeMax:
    UseClassTypes: 0
    SpaceLeaseTypes: 0
    ListingId:
    DateIndicator: 0
    DateEnteredRangeMin: ''
    DateEnteredRangeMax: ''
    MinimumDate: 01/01/0001
    DateEnteredType: RT
    DateFormat: MM/dd/yyyy
    ViewMode: None
    ListingIdPinClick:
    IsUserFromUS: true
    ForceRemoveBoundary: false
    BoundsChangedViaMapInteraction: false
    AgentFirstName:
    AgentLastName:
    Currency:
    ListingType: 1
    IsAuctionsOnly: false
    ResultLimit: 500
    PageNumber: 1
    PageSize: 20
    Timeout: 0
    Origin: 1
    StateKey: 47a2176fb570bab1fe9676718561f6ce
