---
FilterPropertyType: "Land"
FilterState: "VA"
LoopNet:
  criteria:
    LNPropertyTypes: 512
    LNIndustrialSubtypes: 0
    LNRetailSubtypes: 0
    LNShoppingCenterSubtypes: 0
    LNMultiFamilySubtypes: 0
    LNSpecialtySubtypes: 0
    LNOfficeSubtypes: 0
    LNHealthCareSubtypes: 0
    LNHospitalitySubtypes: 0
    LNSportsAndEntertainmentSubtypes: 0
    LNLandSubtypes: 0
    PropertyTypes: 4
    HospitalitySubtypes: 0
    IndustrialSubtypes: 0
    LandTypes: 0
    OfficeSubtypes: 0
    GeneralRetailSubtypes: 0
    FlexSubtypes: 0
    SportsAndEntertainmentSubtypes: 0
    SpecialtySubtypes: 0
    MultifamilySubtypes: 0
    HealthcareSubtypes: 0
    ShoppingCenterTypes: 0
    ApartmentStyleTypes: 0
    Country: USA
    Region: ''
    State: ''
    Market:
    MSA:
    County:
    City: ''
    PostalCode:
    GeographyFilters: []
    PageLocationLabel: Current Polygon(S)
    TypeaheadLocationLabel: Current Polygon(S)
    IncludeProximityCities: false
    AddressLine: ''
    Distance: 0
    Radius:
    CoordinateBounds:
      LatitudeRange:
        Lower: 37.62457647079459
        Upper: 39.446279371654256
      LongitudeRange:
        Lower: -79.87535617344516
        Upper: -75.68407199375766
    Polygon:
      Shapes:
      - - y: 38.52507340280507
          x: -79.15699834312451
        - y: 38.34435224521829
          x: -79.08009404624951
        - y: 38.29263457426046
          x: -79.02516240562451
        - y: 38.249508338978664
          x: -78.88234013999951
        - y: 38.21498891481993
          x: -77.97047490562451
        - y: 38.266761906190816
          x: -77.82765263999951
        - y: 38.266761906190816
          x: -77.28932256187451
        - y: 38.2322506749906
          x: -76.97071904624951
        - y: 38.36158326963076
          x: -77.00367803062451
        - y: 38.39603301609681
          x: -77.04762334312451
        - y: 38.4046428892986
          x: -77.17945928062451
        - y: 38.36158326963076
          x: -77.28932256187451
        - y: 38.3874221174567
          x: -77.35524053062451
        - y: 38.47348495048048
          x: -77.35524053062451
        - y: 38.55944517506446
          x: -77.30030888999951
        - y: 38.73962734196755
          x: -77.04762334312451
        - y: 39.013318480322845
          x: -77.00367803062451
        - y: 39.09863068176349
          x: -77.26734990562451
        - y: 39.14976851723914
          x: -77.59693974937451
        - y: 39.29445736434306
          x: -77.54200810874951
        - y: 39.32845844612018
          x: -77.64088506187451
        - y: 39.32845844612018
          x: -77.69581670249951
        - y: 39.17532351173971
          x: -77.77272099937451
        - y: 39.17532351173971
          x: -77.88258428062451
        - y: 39.37942908575569
          x: -78.10231084312451
        - y: 39.4812587778351
          x: -78.27809209312451
        - y: 39.4812587778351
          x: -78.38795537437451
        - y: 39.226405645710344
          x: -78.33302373374951
        - y: 39.05598746491409
          x: -78.58570928062451
        - y: 38.970623736097714
          x: -78.81642217124951
        - y: 38.62813942896341
          x: -79.12403935874951
        - y: 38.5422613422415
          x: -79.14601201499951
    HasValidCoordinates:
    BuildingClass: 0
    BuildingSizeUom: SquareFeet
    LotSizeUom: Acres
    SubCategoryList:
    - 101
    - 102
    - 105
    - 501
    - 917
    - 503
    - 504
    - 505
    - 507
    - 508
    - 509
    - 512
    - 513
    Editor: Default
    PreserveAddressForRadiusSavedSearch: false
    ListingSearchType: 1
    OnMarketDateRange:
    Keywords:
    Sorting: []
    LoopLinkForLeaseDefaultSorting: []
    LoopLinkForSaleDefaultSorting: []
    LoopLinkForSaleAndLeaseDefaultSorting: []
    PropertyGroupId:
    HasMultipleLocations: false
    IsForSale: true
    PriceRangeMin:
    PriceRangeMax:
    BuildingSizeRangeMin:
    BuildingSizeRangeMax:
    PriceRangeCurrency: USD
    PriceRangeRateType: Total
    LotSizeRangeMin:
    LotSizeRangeMax:
    UnitCountRangeMin:
    UnitCountRangeMax:
    CapRateRangeMin:
    CapRateRangeMax:
    YearBuiltRangeMin:
    YearBuiltRangeMax:
    TermLengthRangeMin:
    TermLengthRangeMax:
    NetLeased: false
    InContract: true
    Distressed: false
    Auction: true
    IsTenXAuctions: false
    AuctionIds:
    Single: false
    Multiple: false
    InvestmentTypeCore: false
    InvestmentTypeValueAdd: false
    InvestmentTypeOpportunistic: false
    InvestmentTypeTripleNet: false
    InvestmentTypeOpportunityZone: false
    AuctionAssetTypeProperties: false
    AuctionAssetTypeNotes: false
    AuctionFinanceTypeFinancing:
    AuctionFinanceTypeBrokerCoOp:
    BusinessForSale: true
    VacantOwner: true
    Investment: true
    InOpportunityZone:
    CondosFilter: 0
    PortfoliosFilter: 0
    ShoppingCenterFilter: 0
    BuildingParkFilter: 0
    IsForLease: false
    LeaseRateRangeMin:
    LeaseRateRangeMax:
    SpaceAvailableRangeMin:
    SpaceAvailableRangeMax:
    LeaseRateTerm:
    SpaceAvailableUom:
    LeaseRateCurrency:
    LeaseRatePerSizeUom:
    SubLease: false
    RegionalMarket:
    SubMarket:
    MoveInDateIndicator: 0
    MoveInDateEnteredType:
    MoveInDateEnteredRangeMin:
    MoveInDateEnteredRangeMax:
    UseClassTypes: 0
    SpaceLeaseTypes: 0
    ListingId:
    DateIndicator: 0
    DateEnteredRangeMin: 01/01/0001
    DateEnteredRangeMax: 01/01/0001
    MinimumDate: 01/01/0001
    DateEnteredType: RT
    DateFormat: MM/dd/yyyy
    ViewMode: None
    ListingIdPinClick:
    IsUserFromUS: true
    ForceRemoveBoundary: false
    BoundsChangedViaMapInteraction: true
    AgentFirstName:
    AgentLastName:
    Currency:
    ListingType: 1
    IsAuctionsOnly: false
    ResultLimit: 500
    PageNumber: 1
    PageSize: 20
    Timeout: 0
    Origin: 1
    StateKey: 5ee0d03564508bf8a9593564d0232789
