---
FilterPropertyType: "Land"
FilterState: "WV"
LoopNet:
  criteria:
    LNPropertyTypes: 512
    LNIndustrialSubtypes: 0
    LNRetailSubtypes: 0
    LNShoppingCenterSubtypes: 0
    LNMultiFamilySubtypes: 0
    LNSpecialtySubtypes: 0
    LNOfficeSubtypes: 0
    LNHealthCareSubtypes: 0
    LNHospitalitySubtypes: 0
    LNSportsAndEntertainmentSubtypes: 0
    LNLandSubtypes: 0
    PropertyTypes: 4
    HospitalitySubtypes: 0
    IndustrialSubtypes: 0
    LandTypes: 0
    OfficeSubtypes: 0
    GeneralRetailSubtypes: 0
    FlexSubtypes: 0
    SportsAndEntertainmentSubtypes: 0
    SpecialtySubtypes: 0
    MultifamilySubtypes: 0
    HealthcareSubtypes: 0
    ShoppingCenterTypes: 0
    ApartmentStyleTypes: 0
    Country: US
    Region: ''
    State: ''
    Market:
    MSA:
    County:
    City: ''
    PostalCode:
    GeographyFilters: []
    PageLocationLabel: Current Polygon(S)
    TypeaheadLocationLabel: Current Polygon(S)
    IncludeProximityCities: false
    AddressLine:
    Distance: 0
    Radius:
    CoordinateBounds:
    Polygon:
      Shapes:
      - - y: 39.151684355903406
          x: -77.84725616373332
        - y: 39.17723865453248
          x: -77.91317413248332
        - y: 39.326120295465
          x: -78.13839385904582
        - y: 39.406809333894394
          x: -78.20980499185832
        - y: 39.46620474531265
          x: -78.34164092935832
        - y: 39.36859983174362
          x: -78.39107940592082
        - y: 39.228319396376904
          x: -78.40755889810832
        - y: 39.074965769739904
          x: -78.48446319498332
        - y: 38.993894454663796
          x: -78.55587432779582
        - y: 38.91700428281592
          x: -78.64925811685832
        - y: 38.89990625017094
          x: -78.75362823404582
        - y: 38.84430920655435
          x: -78.85799835123332
        - y: 38.76297378413757
          x: -78.95138214029582
        - y: 38.69440880393373
          x: -79.13265655435832
        - y: 38.582850420026254
          x: -79.24251983560832
        - y: 38.6043174393169
          x: -79.35238311685832
        - y: 38.66010164229664
          x: -79.34139678873332
        - y: 38.82719367588285
          x: -79.20956085123332
        - y: 38.91273016075088
          x: -79.19308135904582
        - y: 39.070701177355524
          x: -79.08871124185832
        - y: 39.19001232223973
          x: -79.04476592935832
        - y: 39.36010599027583
          x: -78.91842315592082
        - y: 39.54249584424567
          x: -78.84701202310832
        - y: 39.65254619000465
          x: -78.78109405435832
        - y: 39.65254619000465
          x: -78.76461456217082
        - y: 39.5721419831892
          x: -78.74264190592082
        - y: 39.53825964723468
          x: -78.66573760904582
        - y: 39.54673178269523
          x: -78.44601104654582
        - y: 39.65677540328687
          x: -78.36361358560832
        - y: 39.669461490554816
          x: -78.25924346842082
        - y: 39.669461490554816
          x: -78.11092803873332
        - y: 39.610239827064326
          x: -77.78133819498332
        - y: 39.4746856697226
          x: -77.79232452310832
        - y: 39.34736329130235
          x: -77.72091339029582
        - y: 39.24959207462815
          x: -77.71542022623332
        - y: 39.15594405036426
          x: -77.80331085123332
        - y: 39.13890372540923
          x: -77.82528350748332
        - y: 39.14742440358532
          x: -77.83626983560832
    HasValidCoordinates:
    BuildingClass: 0
    BuildingSizeUom: SquareFeet
    LotSizeUom: Acres
    SubCategoryList:
    - 101
    - 102
    - 105
    - 501
    - 917
    - 503
    - 504
    - 505
    - 507
    - 508
    - 509
    - 512
    - 513
    Editor: Default
    PreserveAddressForRadiusSavedSearch: false
    ListingSearchType: 1
    OnMarketDateRange:
    Keywords:
    Sorting: []
    LoopLinkForLeaseDefaultSorting: []
    LoopLinkForSaleDefaultSorting: []
    LoopLinkForSaleAndLeaseDefaultSorting: []
    PropertyGroupId:
    HasMultipleLocations: false
    IsForSale: true
    PriceRangeMin:
    PriceRangeMax:
    BuildingSizeRangeMin:
    BuildingSizeRangeMax:
    PriceRangeCurrency: USD
    PriceRangeRateType: Total
    LotSizeRangeMin:
    LotSizeRangeMax:
    UnitCountRangeMin:
    UnitCountRangeMax:
    CapRateRangeMin:
    CapRateRangeMax:
    YearBuiltRangeMin:
    YearBuiltRangeMax:
    TermLengthRangeMin:
    TermLengthRangeMax:
    NetLeased: false
    InContract: true
    Distressed: false
    Auction: true
    IsTenXAuctions: false
    AuctionIds:
    Single: false
    Multiple: false
    InvestmentTypeCore: false
    InvestmentTypeValueAdd: false
    InvestmentTypeOpportunistic: false
    InvestmentTypeTripleNet: false
    InvestmentTypeOpportunityZone: false
    AuctionAssetTypeProperties: false
    AuctionAssetTypeNotes: false
    AuctionFinanceTypeFinancing:
    AuctionFinanceTypeBrokerCoOp:
    BusinessForSale: true
    VacantOwner: true
    Investment: true
    InOpportunityZone:
    CondosFilter: 0
    PortfoliosFilter: 0
    ShoppingCenterFilter: 0
    BuildingParkFilter: 0
    IsForLease: false
    LeaseRateRangeMin:
    LeaseRateRangeMax:
    SpaceAvailableRangeMin:
    SpaceAvailableRangeMax:
    LeaseRateTerm:
    SpaceAvailableUom:
    LeaseRateCurrency:
    LeaseRatePerSizeUom:
    SubLease: false
    RegionalMarket:
    SubMarket:
    MoveInDateIndicator: 0
    MoveInDateEnteredType:
    MoveInDateEnteredRangeMin:
    MoveInDateEnteredRangeMax:
    UseClassTypes: 0
    SpaceLeaseTypes: 0
    ListingId:
    DateIndicator: 0
    DateEnteredRangeMin: 01/01/0001
    DateEnteredRangeMax: 01/01/0001
    MinimumDate: 01/01/0001
    DateEnteredType: RT
    DateFormat: MM/dd/yyyy
    ViewMode: None
    ListingIdPinClick:
    IsUserFromUS: true
    ForceRemoveBoundary: false
    BoundsChangedViaMapInteraction: true
    AgentFirstName:
    AgentLastName:
    Currency:
    ListingType: 1
    IsAuctionsOnly: false
    ResultLimit: 500
    PageNumber: 1
    PageSize: 20
    Timeout: 0
    Origin: 1
    StateKey: 13fc425dff3208b520cac2844746da83
